-- Seed sample questions with images
INSERT INTO public.questions (test_category, question_text, answer, explanation, image_type, image_path, tags, difficulty)
VALUES 
  ('Driver''s License Preliminary Final Written Test 1', 'The road sign shown indicates a STOP sign. You must come to a complete stop.', true, 'A STOP sign requires drivers to come to a complete stop at the designated line before proceeding.', 'sign', '/src/assets/sign-stop.png', ARRAY['road signs', 'stop', 'regulatory'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign indicates no parking is allowed in this area.', true, 'The no parking sign prohibits vehicles from stopping or parking in the designated area.', 'sign', '/src/assets/sign-no-parking.png', ARRAY['road signs', 'parking', 'regulatory'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign warns of a pedestrian crossing ahead.', true, 'This warning sign alerts drivers to slow down and watch for pedestrians who may be crossing.', 'sign', '/src/assets/sign-pedestrian.png', ARRAY['road signs', 'pedestrian', 'warning'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign indicates a railway crossing ahead.', true, 'Railway crossing signs warn drivers to slow down and be prepared to stop for trains.', 'sign', '/src/assets/sign-railway.png', ARRAY['road signs', 'railway', 'warning'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign indicates the speed limit is 50 km/h.', true, 'Speed limit signs display the maximum speed allowed on that road segment.', 'sign', '/src/assets/sign-speed-50.png', ARRAY['road signs', 'speed limit', 'regulatory'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign warns of bicycle crossing ahead.', true, 'Bicycle crossing signs alert drivers to watch for cyclists who may be crossing the road.', 'sign', '/src/assets/sign-bicycle.png', ARRAY['road signs', 'bicycle', 'warning'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign indicates no entry for all vehicles.', true, 'No entry signs prohibit all vehicles from entering in this direction.', 'sign', '/src/assets/sign-no-entry.png', ARRAY['road signs', 'no entry', 'regulatory'], 'easy'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign indicates priority road ahead.', true, 'Priority road signs indicate that you have the right of way at upcoming intersections.', 'sign', '/src/assets/sign-priority.png', ARRAY['road signs', 'priority', 'regulatory'], 'medium'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign warns of an intersection ahead.', true, 'Intersection warning signs alert drivers to slow down and be prepared for crossing traffic.', 'sign', '/src/assets/sign-intersection.png', ARRAY['road signs', 'intersection', 'warning'], 'medium'),
  ('Driver''s License Preliminary Final Written Test 1', 'This sign indicates you must turn right ahead.', true, 'Mandatory direction signs indicate the required direction of travel.', 'sign', '/src/assets/sign-turn-right.png', ARRAY['road signs', 'turn', 'regulatory'], 'medium')
ON CONFLICT DO NOTHING;